services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testing-management
    restart: always
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test_management
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      db:
        condition: service_healthy

  smtp:
    build:
      context: ./smtp-service
      dockerfile: Dockerfile
    container_name: my-app-smtp
    restart: always
    ports:
      - "2525:25"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test_management
      UPLOAD_DIR: /app/attachments
    volumes:
      - ./public/uploads/mail:/app/attachments
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.6
    container_name: my-app-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test_management
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
